---

- name: Adding repo in source.list 
  become: true
  command: echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list


# below task is giving error. But even without the signature, postresql is working fine
# - name: Importing repo signing key
#   become: true
#   command: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -

- name: Updating apt repo
  become: true
  apt:
    update_cache: true
  
- name: Installing postgresql {{ postgresql_version }}
  become: true
  apt:
    name: postgresql-{{ postgresql_version }}

- name: Starting Postgresql
  become: true
  service:
    name: postgresql
    state: started  