---

- name: Adding NodeSource package
  become: true
  shell: "curl -fsSL https://deb.nodesource.com/setup_{{ nodejs_version }} | bash -"

- name: Installing nodejs in ubuntu server
  become: true
  apt: 
    name: nodejs
    state: present